version: '3'

services:
  app:
    image: myapp:latest
    container_name: myapp
    environment: 
      - PORT=3000
    networks: 
      - creed
    restart: always
networks:
  creed:
    name: creed
